version: '1'

services:
  applio:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8004:7865"
    env_file:
      - .env
    volumes:
      - tts-audio:/tmp/gradio
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  applio: